proxy:
  title: Crispy Apps
  landing-page: /
  port: 8080
  authentication: none
  # Kubernetes specific configuration
  container-backend: kubernetes
  kubernetes:
    url: https://kubernetes.default.svc
    namespace: shinyproxy # Specify the namespace here
    internal-networking: true
    # pod-wait-time: 60000
    image-pull-policy: Always
    image-pull-secret: theia-1in1000-shinyapps # CREATE MANUALLY IF NOT USING KUBERNETES ON DIGITALOCEAN
    # privileged: false # Keep containers unprivileged unless necessary
    # container-protocol: http # Default is suitable for most, switch to https if your app requires secure communication
    # port: 3838 # Default Shiny port, adjust if your app uses a different port
  # heartbeat-rate: 10000
  heartbeat-timeout: 450000
  # container-wait-time: 30000
  specs:
    - id: apps_1in1000_doc
      port: 4000 
      display-name: Apps Documentation
      container-cmd: ["R", "-e", "shiny::runApp(host = \"0.0.0.0\", port = 4000)"]
      container-image: registry.digitalocean.com/theia-1in1000-shinyapps/apps_1in1000_doc:latest
    - id: st_app
      port: 5000 
      display-name: GDP Stress Test
      description: "Banks Climate stress tests on GDP"
      container-cmd: ["R", "-e", "shiny::runApp(host = \"0.0.0.0\", port = 5000)"]
      container-image: registry.digitalocean.com/theia-1in1000-shinyapps/st_app:latest
    - id: equities_app
      port: 6000 
      display-name: Equities Stress Test
      description: "Climate stress test for Equities"
      container-cmd: ["R", "-e", "shiny::runApp(host = \"0.0.0.0\", port = 6000)"]
      container-image: registry.digitalocean.com/theia-1in1000-shinyapps/crispy_app:latest
      container-env:
        TRISK_API_SERVICE: http://trisk-api.default.svc.cluster.local
        CRISPY_MODE: "equity"
      # kubernetes-pod-patches adds the k8s secret db-credentials in the current namespace to the container's env vars
      kubernetes-pod-patches: |
        - op: add
          path: /spec/containers/0/envFrom
          value:
            - secretRef:
                name: db-credentials 
      # container-memory-request: 500Mi
      # container-memory-limit: 1Gi
      # container-cpu-request: 500m
      # container-cpu-limit: 1
    - id: loans_app
      port: 7000 
      display-name: Bonds&Loans Stress Test
      description: "Climate stress test for Bonds&Loans"
      container-cmd: ["R", "-e", "shiny::runApp(host = \"0.0.0.0\", port = 7000)"]
      container-image: registry.digitalocean.com/theia-1in1000-shinyapps/crispy_app:latest
      container-env:
        TRISK_API_SERVICE: http://trisk-api.default.svc.cluster.local
        CRISPY_MODE: "fixed_income"
      # kubernetes-pod-patches adds the k8s secret db-credentials in the current namespace to the container's env vars
      kubernetes-pod-patches: |
        - op: add
          path: /spec/containers/0/envFrom
          value:
            - secretRef:
                name: db-credentials 

logging:
  file:
    name: shinyproxy.log
