apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trisk-api
spec:
  template:
    metadata:
      name: trisk-api-service
      annotations:
        autoscaling.knative.dev/target: "1" # R is single threaded so 1 pod per API connection
        autoscaling.knative.dev/minScale: "2" # Ensure at least two pods are always running        
    spec:
      containers:
        - image: registry.digitalocean.com/theia-1in1000-shinyapps/trisk_api:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault          
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_DB